### ISSUE TITLE
How can I try example plugin?

### ISSUE THREAD

**Issue by agoogli** [c9/c9.ide.example#1]
I would try a simple self-made plugin, just to try...
I placed example directory from github into my plugin dir.

In settings panel, it doesn't find anything, neither if I restart cloud9 and re-try...

B.R.

**Comment by javruben** [comment]
Did you add `?sdk=1` to the url?

**Comment by agoogli** [comment]
I added ?sdk=1 but I've same result

**Comment by javruben** [comment]
you mentioned "your plugin dir". Could you confirm that this is `~/.c9/plugins`?

**Comment by agoogli** [comment]
Yep, I created a plugins directory 

```
~/.c9/plugins
```

I cloned here c9.ide.example directory from github.
I restarted cloud9, but I don't find the plugin in the list into the section ''settings''

**Comment by javruben** [comment]
Did you also add `?debug=2` ? You need to be in debug mode to load arbitrary plugins.

So in full:

`ide.html?debug=2&sdk=1`

**Comment by agoogli** [comment]
Ok, now it works like a charm :D

you can close this
thanks
