### ISSUE TITLE
mysql module installation

### ISSUE THREAD

**Issue by agoogli** [c9/c9.ide.example#2]
I want install mysql module. I run in ~/.c9 directory

```
npm install mysql
```

when in example.js I insert

```
var mysql = require('mysql');
```

firebug shows me a not found package error.
I tried to install it in different places, but I don't solved...

In which position should I install the package?

**Comment by javruben** [comment]
@alessioguglielmo All Cloud9 plugins run in the browser - So _not_ in Node.js on the server.

Please check out our Remote Plugins guide:
http://cloud9-sdk.readme.io/v0.1/docs/remote-plugins

That should explain how to run server side code in Node.js. We just wrote that article yesterday, so any feedback on it is appreciated.
